[config]
schemaVersion = '0.0.1'

[package]
namespace = 'Bergbok'
name = 'Guts'
versionNumber = '1.1.0'
description = 'Lets you resize your needle.'
websiteUrl = 'https://github.com/Bergbok/Silksong-Mods'
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack_Silksong = '5.4.2303'

[build]
icon = './icon.png'
readme = './README.md'
outdir = './tcli-build'
[[build.copy]]
source = './build'
target = '.'

[publish]
repository = 'https://thunderstore.io'
communities = [ 'hollow-knight-silksong' ]
[publish.categories]
hollow-knight-silksong = [ 'audio', 'misc', 'mods', 'tools' ]
