[config]
schemaVersion = '0.0.1'

[package]
namespace = 'Bergbok'
name = 'GunZ'
versionNumber = '0.0.2'
description = 'Lets you animation cancel most actions.'
websiteUrl = 'https://github.com/Bergbok/Silksong-Mods'
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack_Silksong = '5.4.2303'

[build]
icon = './icon.png'
readme = './README.md'
outdir = './tcli-build'
[[build.copy]]
source = './build'
target = '.'

[publish]
repository = 'https://thunderstore.io'
communities = [ 'hollow-knight-silksong' ]
[publish.categories]
hollow-knight-silksong = [ 'misc', 'mods', 'tools' ]
