name: Release

on:
  push:
    tags:
      - "*-v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Get Mod Folder
        id: get-mod-dir
        run: echo "DIR=$(echo ${{ github.ref_name }} | cut -d'-' -f1)" >> $GITHUB_OUTPUT

      - name: Get Version
        id: get-version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^.*-v//')" >> $GITHUB_OUTPUT

      - name: Install dotnet
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: 7

      - name: Build
        run: dotnet build ./${{ steps.get-mod-dir.outputs.DIR }}

      - name: Create archive
        run: |
          mkdir -p ${{ steps.get-mod-dir.outputs.DIR }}/bin/Publish
          zip --junk-paths ${{ steps.get-mod-dir.outputs.DIR }}/bin/Publish/${{ github.ref_name }}.zip ${{ steps.get-mod-dir.outputs.DIR }}/bin/Debug/**/* --exclude *.deps.json

          if [[ ${{steps.get-mod-dir.outputs.DIR}} == "Voicelines" ]]; then
            cd Voicelines
            zip ./bin/Publish/${{ github.ref_name }}.zip ./SFX/*.wav
            cd -
          fi

      - name: Release
        uses: softprops/action-gh-release@v2.3.3
        with:
          name: "${{ steps.get-mod-dir.outputs.DIR }} v${{ steps.get-version.outputs.VERSION }}"
          files: ${{ steps.get-mod-dir.outputs.DIR }}/bin/Publish/*.zip
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: true
